Display loading spinner on log in
RohanKaran/VaultSafe pull request #20
Opened 2022-10-06 20:15 UTC by lejara

### Description

Fixes #7 

If there is anything you want me to change, ill be happy to do so!

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

- Test locally on a chrome browser 

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

P.S. - Don't forget to ⭐ the repo 😉

2022-10-06 21:13 UTC, RohanKaran requested changes

2022-10-06 21:13 UTC, RohanKaran commented on frontend/src/pages/LoginPage.js
> +				Login
Instead of replacing the whole form with spinner just replace this section using conditional operator. And put disabled={loading} in Button to disable the button while loading.
BTW great job!

2022-10-06 22:05 UTC, lejara commented on frontend/src/pages/LoginPage.js
> +				Login
sure thing!

2022-10-06 22:07 UTC, RohanKaran commented
And another thing did consider the scenario when someone enters wrong password. Use the catch in loginUser in AuthContext to disable the loading incase of bad response

2022-10-06 22:11 UTC, lejara commented
True, ill fix it

2022-10-06 22:12 UTC, RohanKaran commented
> True, ill fix it

Cool 🤟

2022-10-07 07:01 UTC, RohanKaran approved these changes
LGTM! Great work 👍🏻

2022-10-07 07:02 UTC, merged